src/Entity/Trip.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TripRepository")
 */
class Trip
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Country")
     * @ORM\JoinColumn(nullable=false)
     */
    private $country;

    /**
     * @ORM\Column(type="date")
     */
    private $date_start;

    /**
     * @ORM\Column(type="date")
     */
    private $date_end;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Picture", mappedBy="trip")
     */
    private $pictures;

    public function __construct()
    {
        $this->pictures = new ArrayCollection();
    }



    public function getId()
    {
        return $this->id;
    }

    public function getCountry(): ?Country
    {
        return $this->country;
    }

    public function setCountry(Country $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->date_start;
    }

    public function setDateStart(\DateTimeInterface $date_start): self
    {
        $this->date_start = $date_start;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->date_end;
    }

    public function setDateEnd(\DateTimeInterface $date_end): self
    {
        $this->date_end = $date_end;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    /**
     * @return Collection|Picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setTrip($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->contains($picture)) {
            $this->pictures->removeElement($picture);
            // set the owning side to null (unless already changed)
            if ($picture->getTrip() === $this) {
                $picture->setTrip(null);
            }
        }

        return $this;
    }


}

src/Form/TripType.php
<?php

namespace App\Form;

use App\Entity\Trip;
use App\Entity\Country;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Form\Extension\Core\Type\TextType;

// import du type nous permettant de gérer le choix d'un pays
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class TripType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date_start')
            ->add('date_end')
            ->add('title', TextType::class)
            ->add('description')
            ->add('price')
            ->add('country', EntityType::class, array(
              'class' => Country::class,
              'choice_label' => 'name',
              'choice_value' => 'id'
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Trip::class,
        ]);
    }
}

src/Controller/TripController.php
<?php

namespace App\Controller;

use App\Entity\Trip;
use App\Entity\Picture;
use App\Form\TripType;
use App\Form\PictureType;
use App\Repository\TripRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/trip")
 */
class TripController extends Controller
{
    /**
     * @Route("/", name="trip_index", methods="GET")
     */
    public function index(TripRepository $tripRepository): Response
    {
        return $this->render('trip/index.html.twig', ['trips' => $tripRepository->findAll()]);
    }

    /**
     * @Route("/new", name="trip_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $trip = new Trip();
        $form = $this->createForm(TripType::class, $trip);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($trip);
            $em->flush();

            return $this->redirectToRoute('trip_index');
        }

        //return new Response('test');
        return $this->render('trip/new.html.twig', [
            'trip' => $trip,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/{id}", name="trip_show", methods="GET")
     */
    public function show(Trip $trip): Response
    {
        return $this->render('trip/show.html.twig', ['trip' => $trip]);
    }

    /**
     * @Route("/{id}/edit", name="trip_edit", methods="GET|POST")
     */
    public function edit(Request $request, Trip $trip): Response
    {
        $form = $this->createForm(TripType::class, $trip);
        $form->handleRequest($request);

        // formulaire photo
        $picture = new Picture(); // création d'un objet vide
        $formPicture = $this->createForm(PictureType::class, $picture);
        $formPicture->handleRequest($request);

        // si le formulaire de mise à jour d'un voyage a été soumis
        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('trip_edit', ['id' => $trip->getId()]);
        }

        // si le formulaire d'ajout de photo a été soumis
        if ($formPicture->isSubmitted() && $formPicture->isValid()) {

          // $file = objet de type UploadedFile
          $file = $formPicture->get('path')->getData();

          // récupération du nom du fichier
          $fileName = $file->getClientOriginalName();

          // déplacement
          $file->move($this->getParameter('pictures_folder'), $fileName);

          // remplissage de la propriété path de la photo
          $picture->setPath($fileName);

          // relation entre le voyage et la photo
          $trip->addPicture($picture);

          // enregistrement de l'image en base de données
          $em = $this->getDoctrine()->getManager();
          $em->persist($picture);
          $em->flush();

          return $this->redirectToRoute('trip_edit', ['id' => $trip->getId()]);
        }

        return $this->render('trip/edit.html.twig', [
            'trip' => $trip,
            'form' => $form->createView(),
            'formPicture' => $formPicture->createView()
        ]);
    }

    /**
     * @Route("/{id}", name="trip_delete", methods="DELETE")
     */
    public function delete(Request $request, Trip $trip): Response
    {
        if ($this->isCsrfTokenValid('delete'.$trip->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($trip);
            $em->flush();
        }

        return $this->redirectToRoute('trip_index');
    }
}

templates/trip/_delete_form.html.twig
<form method="post" action="{{ path('trip_delete', {'id': trip.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ trip.id) }}">
    <button class="btn">Delete</button>
</form>

templates/trip/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/trip/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Trip{% endblock %}

{% block body %}

    <div class="container">
      <div class="row">

        <div class="col-md-6">
          <h3>Modifier le voyage</h3>
          {{ include('trip/_form.html.twig', {'button_label': 'Update'}) }}
          <a href="{{ path('trip_index') }}">Retour à la liste</a>
          {{ include('trip/_delete_form.html.twig') }}
        </div>

        <div class="col-md-6">
          <h3>Ajouter une photo</h3>
          {{ include('picture/new.html.twig') }}

          {% if trip.pictures | length > 0 %}
            {% for picture in trip.pictures %}

              <img
                style="width:100px"
                src="/uploads/pictures/{{picture.path}}" alt="">
            {% endfor %}

          {% else %}
            Aucune photo pour ce voyage
          {% endif %}

        </div>
      </div>
    </div>

{% endblock %}

templates/trip/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Trip index{% endblock %}

{% block body %}
    <h1>Liste des voyages</h1>

    <a
      class="btn btn-primary btn-sm"
      href="{{ path('trip_new') }}">Ajouter un voyage</a>

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Intitulé</th>
                <th>Destination</th>
                <th>Dates</th>
                <th>Prix</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for trip in trips %}
            <tr>
                <td>{{ trip.title }}</td>
                <td>{{ trip.country.name }}</td>
                <td>
                  Du {{ trip.dateStart ? trip.dateStart|date('d/m/Y') : '' }}
                  au {{ trip.dateEnd ? trip.dateEnd|date('d/m/Y') : '' }}
                </td>
                <td>{{ trip.price }} euros</td>
                <td>
                    <a href="{{ path('trip_show', {'id': trip.id}) }}">Détails</a>
                    <a href="{{ path('trip_edit', {'id': trip.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">Aucun voyage enregistré</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/trip/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Trip{% endblock %}

{% block body %}
    <h1>Create new Trip</h1>

    {{ include('trip/_form.html.twig') }}

    <a href="{{ path('trip_index') }}">back to list</a>
{% endblock %}

templates/trip/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Trip{% endblock %}

{% block body %}
    <h1>Trip</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ trip.id }}</td>
            </tr>
            <tr>
                <th>Date_start</th>
                <td>{{ trip.dateStart ? trip.dateStart|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_end</th>
                <td>{{ trip.dateEnd ? trip.dateEnd|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ trip.title }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ trip.description }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ trip.price }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('trip_index') }}">back to list</a>

    <a href="{{ path('trip_edit', {'id': trip.id}) }}">edit</a>

    {{ include('trip/_delete_form.html.twig') }}
{% endblock %}